<?php

namespace App\Controllers;

use App\Controllers\BaseController;

class Testemail extends BaseController
{
	public function index()
	{
		$data=[
			'nombre'	=>	'Elias Moretta',
		];
		$email = \Config\Services::email();
		$to = 'elianosft82@gmail.com';
		$subject = 'Su cuenta Projectrade esta casi lista';
		$message=view('emails/bienvenido_view',$data);
		//$email = config('email');
		$email->setTo($to);
		$email->setFrom('info@projectrade.com','Info');
		$email->setSubject($subject);
		$email->setMessage($message);
		if($email->send())
		{
			echo "La cuenta ha sido creada satisfactoriamente.";
		}else{

			$data = $email->printDebugger(['headers']);
			print_r($data);
		}

	}
	public function email()
	{
		return view('emails/password_view');
	}  
	  /*INSERT INTO `tblPais` VALUES (1, 4, 'Afganistán');
	  INSERT INTO `tblPais` VALUES (2, 248, 'Islas Gland');
	  INSERT INTO `tblPais` VALUES (3, 8, 'Albania');
	  INSERT INTO `tblPais` VALUES (4, 276, 'Alemania');
	  INSERT INTO `tblPais` VALUES (5, 20, 'Andorra');
	  INSERT INTO `tblPais` VALUES (6, 24, 'Angola');
	  INSERT INTO `tblPais` VALUES (7, 660, 'Anguilla');
	  INSERT INTO `tblPais` VALUES (8, 10, 'Antártida');
	  INSERT INTO `tblPais` VALUES (9, 28, 'Antigua y Barbuda');
	  INSERT INTO `tblPais` VALUES (10, 530, 'Antillas Holandesas');
	  INSERT INTO `tblPais` VALUES (11, 682, 'Arabia Saudí');
	  INSERT INTO `tblPais` VALUES (12, 12,'Argelia');
	  INSERT INTO `tblPais` VALUES (13, 32, 'Argentina');
	  INSERT INTO `tblPais` VALUES (14, 51, 'Armenia');
	  INSERT INTO `tblPais` VALUES (15, 533,'Aruba');
	  INSERT INTO `tblPais` VALUES (16, 36,'Australia');
	  INSERT INTO `tblPais` VALUES (17, 40,'Austria');
	  INSERT INTO `tblPais` VALUES (18, 31,'Azerbaiyán');
	  INSERT INTO `tblPais` VALUES (19, 44,'Bahamas');
	  INSERT INTO `tblPais` VALUES (20, 48,'Bahréin');
	  INSERT INTO `tblPais` VALUES (21, 50,'Bangladesh');
	  INSERT INTO `tblPais` VALUES (22, 52,'Barbados');
	  INSERT INTO `tblPais` VALUES (23, 112,'Bielorrusia');
	  INSERT INTO `tblPais` VALUES (24, 56,'Bélgica');
	  INSERT INTO `tblPais` VALUES (25, 84,'Belice');
	  INSERT INTO `tblPais` VALUES (26, 204,'Benin');
	  INSERT INTO `tblPais` VALUES (27, 60,'Bermudas');
	  INSERT INTO `tblPais` VALUES (28, 64,'Bhután');
	  INSERT INTO `tblPais` VALUES (29, 68,'Bolivia');
	  INSERT INTO `tblPais` VALUES (30, 70,'Bosnia y Herzegovina');
	  INSERT INTO `tblPais` VALUES (31, 72,'Botsuana');
	  INSERT INTO `tblPais` VALUES (32, 74,'Isla Bouvet');
	  INSERT INTO `tblPais` VALUES (33, 76,'Brasil');
	  INSERT INTO `tblPais` VALUES (34, 96,'Brunéi');
	  INSERT INTO `tblPais` VALUES (35, 100,'Bulgaria');
	  INSERT INTO `tblPais` VALUES (36, 854,'Burkina Faso');
	  INSERT INTO `tblPais` VALUES (37, 108, 'Burundi');
	  INSERT INTO `tblPais` VALUES (38, 132, 'Cabo Verde');
	  INSERT INTO `tblPais` VALUES (39, 136, 'Islas Caimán');
	  INSERT INTO `tblPais` VALUES (40, 116, 'Camboya');
	  INSERT INTO `tblPais` VALUES (41, 120,'Camerún');
	  INSERT INTO `tblPais` VALUES (42, 124,'Canadá');
	  INSERT INTO `tblPais` VALUES (43, 140,'República Centroafricana');
	  INSERT INTO `tblPais` VALUES (44, 148,'Chad');
	  INSERT INTO `tblPais` VALUES (45, 203,'República Checa');
	  INSERT INTO `tblPais` VALUES (46, 152,'Chile');
	  INSERT INTO `tblPais` VALUES (47, 156,'China');
	  INSERT INTO `tblPais` VALUES (48, 196,'Chipre');
	  INSERT INTO `tblPais` VALUES (49, 162,'Isla de Navidad');
	  INSERT INTO `tblPais` VALUES (50, 336, 'Ciudad del Vaticano');
	  INSERT INTO `tblPais` VALUES (51, 166, 'Islas Cocos');
	  INSERT INTO `tblPais` VALUES (52, 170, 'Colombia');
	  INSERT INTO `tblPais` VALUES (53, 174, 'Comoras');
	  INSERT INTO `tblPais` VALUES (54, 180, 'República Democrática del Congo');
	  INSERT INTO `tblPais` VALUES (55, 178, 'Congo');
	  INSERT INTO `tblPais` VALUES (56, 184, 'Islas Cook');
	  INSERT INTO `tblPais` VALUES (57, 408, 'Corea del Norte');
	  INSERT INTO `tblPais` VALUES (58, 410, 'Corea del Sur');
	  INSERT INTO `tblPais` VALUES (59, 384, 'Costa de Marfil');
	  INSERT INTO `tblPais` VALUES (60, 188, 'Costa Rica');
	  INSERT INTO `tblPais` VALUES (61, 191, 'Croacia');
	  INSERT INTO `tblPais` VALUES (62, 192, 'Cuba');
	  INSERT INTO `tblPais` VALUES (63, 208, 'Dinamarca');
	  INSERT INTO `tblPais` VALUES (64, 212, 'Dominica');
	  INSERT INTO `tblPais` VALUES (65, 214, 'República Dominicana');
	  INSERT INTO `tblPais` VALUES (66, 218, 'Ecuador');
	  INSERT INTO `tblPais` VALUES (67, 818, 'Egipto');
	  INSERT INTO `tblPais` VALUES (68, 222, 'El Salvador');
	  INSERT INTO `tblPais` VALUES (69, 784, 'Emiratos Árabes Unidos');
	  INSERT INTO `tblPais` VALUES (70, 232, 'Eritrea');
	  INSERT INTO `tblPais` VALUES (71, 703, 'Eslovaquia');
	  INSERT INTO `tblPais` VALUES (72, 705, 'Eslovenia');
	  INSERT INTO `tblPais` VALUES (73, 724, 'España');
	  INSERT INTO `tblPais` VALUES (74, 581, 'Islas ultramarinas de Estados Unidos');
	  INSERT INTO `tblPais` VALUES (75, 840, 'Estados Unidos');
	  INSERT INTO `tblPais` VALUES (76, 233, 'Estonia');
	  INSERT INTO `tblPais` VALUES (77, 231, 'Etiopía');
	  INSERT INTO `tblPais` VALUES (78, 234, 'Islas Feroe');
	  INSERT INTO `tblPais` VALUES (79, 608, 'Filipinas');
	  INSERT INTO `tblPais` VALUES (80, 246, 'Finlandia');
	  INSERT INTO `tblPais` VALUES (81, 242, 'Fiyi');
	  INSERT INTO `tblPais` VALUES (82, 250, 'Francia');
	  INSERT INTO `tblPais` VALUES (83, 266, 'Gabón');
	  INSERT INTO `tblPais` VALUES (84, 270, 'Gambia');
	  INSERT INTO `tblPais` VALUES (85, 268, 'Georgia');
	  INSERT INTO `tblPais` VALUES (86, 239, 'Islas Georgias del Sur y Sandwich del Sur');
	  INSERT INTO `tblPais` VALUES (87, 288, 'Ghana');
	  INSERT INTO `tblPais` VALUES (88, 292, 'Gibraltar');
	  INSERT INTO `tblPais` VALUES (89, 308, 'Granada');
	  INSERT INTO `tblPais` VALUES (90, 300, 'Grecia');
	  INSERT INTO `tblPais` VALUES (91, 304, 'Groenlandia');
	  INSERT INTO `tblPais` VALUES (92, 312, 'Guadalupe');
	  INSERT INTO `tblPais` VALUES (93, 316, 'Guam');
	  INSERT INTO `tblPais` VALUES (94, 320, 'Guatemala');
	  INSERT INTO `tblPais` VALUES (95, 254, 'Guayana Francesa');
	  INSERT INTO `tblPais` VALUES (96, 324, 'Guinea');
	  INSERT INTO `tblPais` VALUES (97, 226, 'Guinea Ecuatorial');
	  INSERT INTO `tblPais` VALUES (98, 624, 'Guinea-Bissau');
	  INSERT INTO `tblPais` VALUES (99, 328, 'Guyana');
	  INSERT INTO `tblPais` VALUES (100, 332, 'Haití');
	  INSERT INTO `tblPais` VALUES (101, 334, 'Islas Heard y McDonald');
	  INSERT INTO `tblPais` VALUES (102, 340, 'Honduras');
	  INSERT INTO `tblPais` VALUES (103, 344, 'Hong Kong');
	  INSERT INTO `tblPais` VALUES (104, 348, 'Hungría');
	  INSERT INTO `tblPais` VALUES (105, 356, 'India');
	  INSERT INTO `tblPais` VALUES (106, 360, 'Indonesia');
	  INSERT INTO `tblPais` VALUES (107, 364, 'Irán');
	  INSERT INTO `tblPais` VALUES (108, 368, 'Iraq');
	  INSERT INTO `tblPais` VALUES (109, 372, 'Irlanda');
	  INSERT INTO `tblPais` VALUES (110, 352, 'Islandia');
	  INSERT INTO `tblPais` VALUES (111, 376, 'Israel');
	  INSERT INTO `tblPais` VALUES (112, 380, 'Italia');
	  INSERT INTO `tblPais` VALUES (113, 388, 'Jamaica');
	  INSERT INTO `tblPais` VALUES (114, 392, 'Japón');
	  INSERT INTO `tblPais` VALUES (115, 400, 'Jordania');
	  INSERT INTO `tblPais` VALUES (116, 398, 'Kazajstán');
	  INSERT INTO `tblPais` VALUES (117, 404, 'Kenia');
	  INSERT INTO `tblPais` VALUES (118, 417, 'Kirguistán');
	  INSERT INTO `tblPais` VALUES (119, 296, 'Kiribati');
	  INSERT INTO `tblPais` VALUES (120, 414, 'Kuwait');
	  INSERT INTO `tblPais` VALUES (121, 418, 'Laos');
	  INSERT INTO `tblPais` VALUES (122, 426, 'Lesotho');
	  INSERT INTO `tblPais` VALUES (123, 428, 'Letonia');
	  INSERT INTO `tblPais` VALUES (124, 422, 'Líbano');
	  INSERT INTO `tblPais` VALUES (125, 430, 'Liberia');
	  INSERT INTO `tblPais` VALUES (126, 434, 'Libia');
	  INSERT INTO `tblPais` VALUES (127, 438, 'Liechtenstein');
	  INSERT INTO `tblPais` VALUES (128, 440, 'Lituania');
	  INSERT INTO `tblPais` VALUES (129, 442, 'Luxemburgo');
	  INSERT INTO `tblPais` VALUES (130, 446, 'Macao');
	  INSERT INTO `tblPais` VALUES (131, 807, 'ARY Macedonia');
	  INSERT INTO `tblPais` VALUES (132, 450, 'Madagascar');
	  INSERT INTO `tblPais` VALUES (133, 458, 'Malasia');
	  INSERT INTO `tblPais` VALUES (134, 454, 'Malawi');
	  INSERT INTO `tblPais` VALUES (135, 462, 'Maldivas');
	  INSERT INTO `tblPais` VALUES (136, 466, 'Malí');
	  INSERT INTO `tblPais` VALUES (137, 470, 'Malta');
	  INSERT INTO `tblPais` VALUES (138, 238, 'Islas Malvinas');
	  INSERT INTO `tblPais` VALUES (139, 580, 'Islas Marianas del Norte');
	  INSERT INTO `tblPais` VALUES (140, 504, 'Marruecos');
	  INSERT INTO `tblPais` VALUES (141, 584, 'Islas Marshall');
	  INSERT INTO `tblPais` VALUES (142, 474, 'Martinica');
	  INSERT INTO `tblPais` VALUES (143, 480, 'Mauricio');
	  INSERT INTO `tblPais` VALUES (144, 478, 'Mauritania');
	  INSERT INTO `tblPais` VALUES (145, 175, 'Mayotte');
	  INSERT INTO `tblPais` VALUES (146, 484, 'México');
	  INSERT INTO `tblPais` VALUES (147, 583, 'Micronesia');
	  INSERT INTO `tblPais` VALUES (148, 498, 'Moldavia');
	  INSERT INTO `tblPais` VALUES (149, 492, 'Mónaco');
	  INSERT INTO `tblPais` VALUES (150, 496, 'Mongolia');
	  INSERT INTO `tblPais` VALUES (151, 500, 'Montserrat');
	  INSERT INTO `tblPais` VALUES (152, 508, 'Mozambique');
	  INSERT INTO `tblPais` VALUES (153, 104, 'Myanmar');
	  INSERT INTO `tblPais` VALUES (154, 516, 'Namibia');
	  INSERT INTO `tblPais` VALUES (155, 520, 'Nauru');
	  INSERT INTO `tblPais` VALUES (156, 524, 'Nepal');
	  INSERT INTO `tblPais` VALUES (157, 558, 'Nicaragua');
	  INSERT INTO `tblPais` VALUES (158, 562, 'Níger');
	  INSERT INTO `tblPais` VALUES (159, 566, 'Nigeria');
	  INSERT INTO `tblPais` VALUES (160, 570, 'Niue');
	  INSERT INTO `tblPais` VALUES (161, 574, 'Isla Norfolk');
	  INSERT INTO `tblPais` VALUES (162, 578, 'Noruega');
	  INSERT INTO `tblPais` VALUES (163, 540, 'Nueva Caledonia');
	  INSERT INTO `tblPais` VALUES (164, 554, 'Nueva Zelanda');
	  INSERT INTO `tblPais` VALUES (165, 512, 'Omán');
	  INSERT INTO `tblPais` VALUES (166, 528, 'Países Bajos');
	  INSERT INTO `tblPais` VALUES (167, 586, 'Pakistán');
	  INSERT INTO `tblPais` VALUES (168, 585, 'Palau');
	  INSERT INTO `tblPais` VALUES (169, 275, 'Palestina');
	  INSERT INTO `tblPais` VALUES (170, 591, 'Panamá');
	  INSERT INTO `tblPais` VALUES (171, 598, 'Papúa Nueva Guinea');
	  INSERT INTO `tblPais` VALUES (172, 600, 'Paraguay');
	  INSERT INTO `tblPais` VALUES (173, 604, 'Perú');
	  INSERT INTO `tblPais` VALUES (174, 612, 'Islas Pitcairn');
	  INSERT INTO `tblPais` VALUES (175, 258, 'Polinesia Francesa');
	  INSERT INTO `tblPais` VALUES (176, 616, 'Polonia');
	  INSERT INTO `tblPais` VALUES (177, 620, 'Portugal');
	  INSERT INTO `tblPais` VALUES (178, 630, 'Puerto Rico');
	  INSERT INTO `tblPais` VALUES (179, 634, 'Qatar');
	  INSERT INTO `tblPais` VALUES (180, 826, 'Reino Unido');
	  INSERT INTO `tblPais` VALUES (181, 638, 'Reunión');
	  INSERT INTO `tblPais` VALUES (182, 646, 'Ruanda');
	  INSERT INTO `tblPais` VALUES (183, 642, 'Rumania');
	  INSERT INTO `tblPais` VALUES (184, 643, 'Rusia');
	  INSERT INTO `tblPais` VALUES (185, 732, 'Sahara Occidental');
	  INSERT INTO `tblPais` VALUES (186, 90,  'Islas Salomón');
	  INSERT INTO `tblPais` VALUES (187, 882, 'Samoa');
	  INSERT INTO `tblPais` VALUES (188, 16, 'Samoa Americana');
	  INSERT INTO `tblPais` VALUES (189, 659, 'San Cristóbal y Nevis');
	  INSERT INTO `tblPais` VALUES (190, 674, 'San Marino');
	  INSERT INTO `tblPais` VALUES (191, 666, 'San Pedro y Miquelón');
	  INSERT INTO `tblPais` VALUES (192, 670, 'San Vicente y las Granadinas');
	  INSERT INTO `tblPais` VALUES (193, 654, 'Santa Helena');
	  INSERT INTO `tblPais` VALUES (194, 662, 'Santa Lucía');
	  INSERT INTO `tblPais` VALUES (195, 678, 'Santo Tomé y Príncipe');
	  INSERT INTO `tblPais` VALUES (196, 686, 'Senegal');
	  INSERT INTO `tblPais` VALUES (197, 891, 'Serbia y Montenegro');
	  INSERT INTO `tblPais` VALUES (198, 690, 'Seychelles');
	  INSERT INTO `tblPais` VALUES (199, 694, 'Sierra Leona');
	  INSERT INTO `tblPais` VALUES (200, 702, 'Singapur');
	  INSERT INTO `tblPais` VALUES (201, 760, 'Siria');
	  INSERT INTO `tblPais` VALUES (202, 706, 'Somalia');
	  INSERT INTO `tblPais` VALUES (203, 144, 'Sri Lanka');
	  INSERT INTO `tblPais` VALUES (204, 748, 'Suazilandia');
	  INSERT INTO `tblPais` VALUES (205, 710, 'Sudáfrica');
	  INSERT INTO `tblPais` VALUES (206, 736, 'Sudán');
	  INSERT INTO `tblPais` VALUES (207, 752, 'Suecia');
	  INSERT INTO `tblPais` VALUES (208, 756, 'Suiza');
	  INSERT INTO `tblPais` VALUES (209, 740, 'Surinam');
	  INSERT INTO `tblPais` VALUES (210, 744, 'Svalbard y Jan Mayen');
	  INSERT INTO `tblPais` VALUES (211, 764, 'Tailandia');
	  INSERT INTO `tblPais` VALUES (212, 158, 'Taiwán');
	  INSERT INTO `tblPais` VALUES (213, 834, 'Tanzania');
	  INSERT INTO `tblPais` VALUES (214, 762, 'Tayikistán');
	  INSERT INTO `tblPais` VALUES (215, 86, 'Territorio Británico del Océano Índico');
	  INSERT INTO `tblPais` VALUES (216, 260, 'Territorios Australes Franceses');
	  INSERT INTO `tblPais` VALUES (217, 626, 'Timor Oriental');
	  INSERT INTO `tblPais` VALUES (218, 768, 'Togo');
	  INSERT INTO `tblPais` VALUES (219, 772, 'Tokelau');
	  INSERT INTO `tblPais` VALUES (220, 776, 'Tonga');
	  INSERT INTO `tblPais` VALUES (221, 780, 'Trinidad y Tobago');
	  INSERT INTO `tblPais` VALUES (222, 788, 'Túnez');
	  INSERT INTO `tblPais` VALUES (223, 796, 'Islas Turcas y Caicos');
	  INSERT INTO `tblPais` VALUES (224, 795, 'Turkmenistán');
	  INSERT INTO `tblPais` VALUES (225, 792, 'Turquía');
	  INSERT INTO `tblPais` VALUES (226, 798, 'Tuvalu');
	  INSERT INTO `tblPais` VALUES (227, 804, 'Ucrania');
	  INSERT INTO `tblPais` VALUES (228, 800, 'Uganda');
	  INSERT INTO `tblPais` VALUES (229, 858, 'Uruguay');
	  INSERT INTO `tblPais` VALUES (230, 860, 'Uzbekistán');
	  INSERT INTO `tblPais` VALUES (231, 548, 'Vanuatu');
	  INSERT INTO `tblPais` VALUES (232, 862, 'Venezuela');
	  INSERT INTO `tblPais` VALUES (233, 704, 'Vietnam');
	  INSERT INTO `tblPais` VALUES (234, 92,  'Islas Vírgenes Británicas');
	  INSERT INTO `tblPais` VALUES (235, 850, 'Islas Vírgenes de los Estados Unidos');
	  INSERT INTO `tblPais` VALUES (236, 876, 'Wallis y Futuna');
	  INSERT INTO `tblPais` VALUES (237, 887, 'Yemen');
	  INSERT INTO `tblPais` VALUES (238, 262, 'Yibuti');
	  INSERT INTO `tblPais` VALUES (239, 894, 'Zambia');
	  INSERT INTO `tblPais` VALUES (240, 716, 'Zimbabue');*/
	  
}
